version: "2.3.3"

services:
  app:
    build:
      context: "."
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    # sh -c means you're running a shell command
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8080"

# to create django app, run:
# docker-compose run app sh -c "django-admin startproject app ."
