# Generated by Django 3.2.12 on 2022-04-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prices',
            new_name='price',
        ),
    ]
