# Generated by Django 3.2.12 on 2022-04-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_prices_recipe_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='links',
            new_name='link',
        ),
    ]
